packages:
  - examples/client
  - examples/client/microfrontends/*
  - examples/ssr

allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  lmdb: false
  msgpackr-extract: false
  sharp: false
  workerd: true
minimumReleaseAgeExclude:
  - '@comp0/core@0.1.0-next.11'
  - '@comp0/react@0.1.0-next.11'
onlyBuiltDependencies:
  - esbuild
